CREATE PROCEDURE FI_SP_ConsCliente
    @ID BIGINT
AS
BEGIN
    IF ISNULL(@ID, 0) = 0
BEGIN
SELECT C.NOME, C.SOBRENOME, C.NACIONALIDADE, C.CEP, C.ESTADO, C.CIDADE, C.LOGRADOURO, C.EMAIL, C.TELEFONE, C.CPF, C.ID,
       B.ID AS ID_Beneficiario, B.CPF AS CPF_Beneficiario, B.NOME AS Nome_Beneficiario
FROM CLIENTES C
         LEFT JOIN BENEFICIARIOS B ON C.ID = B.IdCliente
END
ELSE
BEGIN
SELECT C.NOME, C.SOBRENOME, C.NACIONALIDADE, C.CEP, C.ESTADO, C.CIDADE, C.LOGRADOURO, C.EMAIL, C.TELEFONE, C.CPF, C.ID,
       B.ID AS ID_Beneficiario, B.CPF AS CPF_Beneficiario, B.NOME AS Nome_Beneficiario  
FROM CLIENTES C
         LEFT JOIN BENEFICIARIOS B ON C.ID = B.IdCliente
WHERE C.ID = @ID
END
END
